<a href="https://colab.research.google.com/github/makbd71/Pyhton_learning/blob/main/Data_Manipulation_%26_aggregation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Data_Manipulation & aggregation

In [2]:
import pandas as pd
df = pd.read_csv('/Order.csv')

print(df)

                           Region               Country    ItemType  \
0    Middle East and North Africa                 Libya   Cosmetics
1                   North America                Canada  Vegetables
2    Middle East and North Africa                 Libya   Baby Food
3                            Asia                 Japan      Cereal
4              Sub-Saharan Africa                  Chad      Fruits
..                            ...                   ...         ...
995  Middle East and North Africa            Azerbaijan      Snacks
996                        Europe               Georgia   Baby Food
997  Middle East and North Africa  United Arab Emirates  Vegetables
998                        Europe               Finland   Household
999                        Europe              Portugal      Cereal

    SalesChannel OrderPriority    OrderID  UnitsSold  UnitPrice  UnitCost  \
0        Offline             M  686800706       8446     437.20    263.33
1         Online             M  185941302       3018     154.06     90.93
2        Offline             C  246222341       1517     255.28    159.42
3        Offline             C  161442649       3322     205.70    117.11
4        Offline             H  645713555       9845       9.33      6.92
..           ...           ...        ...        ...        ...       ...
995      Offline             C  534085166       6524     152.58     97.44
996      Offline             H  590768182        288     255.28    159.42
997       Online             C  524363124       9556     154.06     90.93
998      Offline             L  289606320       9801     668.27    502.54
999      Offline             C  811546599       3528     205.70    117.11

     TotalRevenue   TotalCost  TotalProfit
0      3692591.20  2224085.18   1468506.02
1       464953.08   274426.74    190526.34
2       387259.76   241840.14    145419.62
3       683335.40   389039.42    294295.98
4        91853.85    68127.40     23726.45
..            ...         ...          ...
995     995431.92   635698.56    359733.36
996      73520.64    45912.96     27607.68
997    1472197.36   868927.08    603270.28
998    6549714.27  4925394.54   1624319.73
999     725709.60   413164.08    312545.52

[1000 rows x 12 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [11]:
#Another duplicate fuction, drop all the duplicate values

df_new = df.drop_duplicates()

In [13]:
avg_sale = df_new.groupby('ItemType')['UnitsSold'].mean()
print(avg_sale)

ItemType
Baby Food          5018.597701
Beverages          4999.059406
Cereal             4908.215190
Clothes            4845.974359
Cosmetics          5680.960000
Fruits             5073.214286
Household          4818.077922
Meat               5229.679487
Office Supplies    4994.179775
Personal Care      5468.091954
Snacks             4818.829268
Vegetables         4858.515464
Name: UnitsSold, dtype: float64

In [23]:
#acg_sales by region

avg_sales_region = df_new.groupby('Region')['TotalProfit'].sum()
print(avg_sales_region)

Region
Asia                                 5.079940e+07
Australia and Oceania                3.187842e+07
Central America and the Caribbean    4.133678e+07
Europe                               1.067720e+08
Middle East and North Africa         5.105699e+07
North America                        7.708059e+06
Sub-Saharan Africa                   1.016510e+08
Name: TotalProfit, dtype: float64

In [28]:
#sum_sales by region

sum_sales_region = df_new.groupby('Region')['TotalProfit'].sum()
print(sum_sales_region)

Region
Asia                                 5.079940e+07
Australia and Oceania                3.187842e+07
Central America and the Caribbean    4.133678e+07
Europe                               1.067720e+08
Middle East and North Africa         5.105699e+07
North America                        7.708059e+06
Sub-Saharan Africa                   1.016510e+08
Name: TotalProfit, dtype: float64

In [29]:
#avg_sales by region

avg_sales_region = df_new.groupby('Region')['TotalProfit'].mean()
print(avg_sales_region)

Region
Asia                                 373524.993382
Australia and Oceania                403524.313038
Central America and the Caribbean    417543.214242
Europe                               399895.012921
Middle East and North Africa         369978.212609
North America                        405687.330000
Sub-Saharan Africa                   387980.887252
Name: TotalProfit, dtype: float64

In [30]:
df_new.aggregate(['sum','min'])

,Region,Country,ItemType,SalesChannel,OrderPriority,OrderID,UnitsSold,UnitPrice,UnitCost,TotalRevenue,TotalCost,TotalProfit
sum,Middle East and North AfricaNorth AmericaMiddl...,LibyaCanadaLibyaJapanChadArmeniaEritreaMontene...,CosmeticsVegetablesBaby FoodCerealFruitsCereal...,OfflineOnlineOfflineOfflineOfflineOnlineOnline...,MMCCHHHMHHMMCCLHHMCLCLHLHMMMHCCHLMLMHMLLCMLLLM...,549681324743,5053988,262106.84,184965.11,1.327322e+09,9.361192e+08,3.912026e+08
min,Asia,Afghanistan,Baby Food,Offline,C,102928006,13,9.33,6.92,2.043250e+03,1.416750e+03,5.326100e+02

In [34]:
#information only for column UnitsSold

df_new['UnitsSold'].aggregate(['sum','min'])

sum    5053988
min         13
Name: UnitsSold, dtype: int64

In [ ]:
#marge 2 column based one the order_ID

new_order_file = pd.read.csv('') ##need to collected and upload, which wasn't available , the new order file.
merged_data =pd.merge(new_df,new_order_file on = 'OrderID')

print(merged_data)